"""Initial migration.

Revision ID: 55e875f6be2f
Revises: d97029e6745f
Create Date: 2025-01-19 17:05:04.114681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e875f6be2f'
down_revision = 'd97029e6745f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_approveed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approveed', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
